# Copyright 2026 Qore Technologies, s.r.o.; SPDX-License-Identifier: MIT
from pathlib import Path
import collections,gzip,hashlib,json,re,runpy,shutil
root=Path.cwd();out=root/'evidence/controls/pyarrow-devel-20261008';build=root/'results/leap-python-pyarrow-devel-candidate4-20261008';installed=root/'results/pyarrow-devel-qualification4-20261008'
b=json.loads((build/'build.json').read_text());assert b['exit_code']==0
for n,h in b['source']['sources'].items():
 p=root/'dependencies'/n
 if p.exists():assert hashlib.sha256(p.read_bytes()).hexdigest()==h,n
for n,h in b['artifacts'].items():
 with (build/n).open('rb') as stream:assert hashlib.file_digest(stream,'sha256').hexdigest()==h,n
old=json.loads((root/'evidence/pyarrow-external-diagnostics-20261003.json').read_text())['warning_inventory'];text=(build/'build.log').read_text()
def norm(s):
 s=re.sub(r'/work/rpmbuild/BUILD/[^ ]*?/apache-arrow-25.0.1/','<source>/',s.strip());return re.sub(r'/tmp/[^/]+/build/','<generated>/',s)
new=[l for l in text.splitlines() if ': warning:' in l];assert collections.Counter(map(norm,old))==collections.Counter(map(norm,new));assert '6616 passed, 1646 skipped, 13 xfailed, 1 xpassed' in text
r=json.loads((installed/'status.json').read_text());assert len(r['steps'])==4 and all(s['exit_code']==0 for s in r['steps']);assert '0 errors, 0 warnings' in (installed/'lint.log').read_text()
assert 'PASS: ownership, runtime upgrade, SDK consumer, SDK removal and target RPM lint' in (root/'results/pyarrow-devel-candidate4-driver-20261008.log').read_text()
for n in ('runtime-upgrade','sdk-consumer-and-removal'):assert not re.search(r'warning:|Warning:',(installed/(n+'.log')).read_text())
paths={n:build/n for n in ('build.log','build.json','installed-packages.txt')}
paths.update({n:installed/n for n in ('status.json','ownership.json','ownership.log','runtime-upgrade.log','sdk-consumer-and-removal.log','lint.log','consumer.pyx')})
paths.update({n:root/'results'/n for n in ('pyarrow-devel-final-spec-query-20261008.log','pyarrow-native-lint-inventory-20261008.json','pyarrow-devel-initial-lint-20261008.log','pyarrow-devel-sdk-prerequisite-control-20261008.log')})
paths['initial-sdk-missing-numpy.log']=root/'results/pyarrow-devel-qualification-20261008/sdk-consumer-and-removal.log'
for name,p in paths.items():
 if name.endswith(('.log','.json','.txt')):(out/(name+'.gz')).write_bytes(gzip.compress(p.read_bytes(),mtime=0))
 else:shutil.copyfile(p,out/name)
(out/'record.py').write_bytes(Path(__file__).read_bytes())
record={'schema':1,'date':'2026-10-08','copyright':'Copyright 2026 Qore Technologies, s.r.o.','status':'Final local RPMs and installed artifact qualification pass; audited source ready for committed native OBS delivery.','root_causes':['Both native builds shipped 395 development headers in the runtime RPM and a zero-byte Cython marker.','The new development package needs Python and NumPy headers, matching shared Arrow headers, the exact PyArrow runtime and the interpreter ABI; header-only files do not generate a Python ABI dependency automatically.'],'fix':['Move pyarrow/include and pyarrow/src to python313-pyarrow-devel; preserve runtime Cython declarations.','Keep the package marker with an explanatory Apache-licensed comment.','Declare actual SDK dependencies. Normal RPM expansion preserves the flavor-independent python(abi) capability name.'],'source':b['source'],'image':b['image'],'artifacts':b['artifacts'],'tests':{'api':3,'upstream_passed':6616,'optional_skips':1646,'upstream_expected_failures':13,'upstream_nonstrict_unexpected_pass':1,'exact_approved_compiler_diagnostics':24,'installed_runtime_phases':3,'api_cases_each_phase':3,'cython_consumer':'Compilation, linking and execution: empty, null, mixed and1024-element arrays plus invalid-type rejection.','ownership':json.loads((installed/'ownership.json').read_text()),'lint_errors':0,'lint_warnings':0},'controls':['Original native lint rejects all395 runtime headers and empty marker.','Initial consumer failed at the missing NumPy header; the corrected SDK and include paths compile and run successfully.','Initial lint reported one missing ABI requirement despite process exit0; the qualifier now also rejects nonzero diagnostic totals.','Runtime upgrades without devel, Python headers or compiler; removing devel preserves the three API regressions.'],'fixture_corrections':['Initial build image lacked build requirements; created a pinned complete image and rebuilt without bypassing dependency checks.','Corrected the ownership JSON newline encoding before final qualification.','Cancelled obsolete candidate3 after the ABI requirement was root-caused; source/logs preserved, discarded build scratch removed.'],'retained_diagnostics':'Only the exact24 upstream deprecations accepted in evidence/pyarrow-external-diagnostics-20261003.json; normalized compiler message multisets match exactly.','limits':'Packaging-only change; no native implementation changes or new Valgrind claim. Native x86_64/aarch64 rebuilds and Leap gRPC integration remain required. No new lint filters.','changed_files_sha256':{p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in ('dependencies/python-pyarrow.spec','dependencies/arrow-flight.rst')},'files_sha256':{str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in out.iterdir()}}
(root/'evidence/pyarrow-devel-20261008.json').write_text(json.dumps(record,indent=2)+'\n')
runpy.run_path('work/write-scoped-audit.py')['write'](root/'audits/pyarrow-devel-20261008.rst','PyArrow development package audit','Scope: runtime/development file split, dependency metadata, Cython marker documentation and installed qualification. All62 checks:11 Pass,51 N/A,0 Fail. Full upstream and installed checks pass; exact previously approved24 upstream compiler deprecations retained. No C++ implementation changes, so Valgrind is not applicable.',{9:'New marker, guide, qualifier and evidence carry Copyright2026.',14:'Qualification helper has an executable bit and interpreter directive.',53:'Correct package ownership and actualSDK dependencies. No files discarded, filters added, tests disabled or compiler flags changed.',54:'Subprocess failures propagate; log handles are scoped and disposable containers removed. Artifact/source hashes checked before installation.',55:'Each qualification phase uses a separate disposable container and scoped fixture files.',56:'Path objects and structured command arguments; RPM dependencies verified from real artifacts.',57:'Set-based file ownership checks; one linear pass through artifact hashes and source diagnostics.',58:'Check missing headers, incorrect dependencies, invalid array types, SDK removal and nonzero lint totals even when rpmlint exits0.',59:'arrow-flight.rst documents runtime vsSDK installation and allthree extension include directories; spec changelog records changes.',61:'Exact pinned source/artifact hashes, network-disabledbuilds/tests, no compiler inruntime-onlyfixture and no warningfilters.',62:'3API and6616upstream tests pass. All395headers live exclusively indevel, exactdependencies verified; actualCythonconsumer andruntimeafterdevelremovalpass; targetlintzeroerrors/zerowarnings.'},'No corresponding runtime C++, Qore/QPP module, DataProvider, JNI, sandbox, cancellation or publicAPI implementation change in this package metadata/file-ownership scope.')
print('PyArrow source/artifacts and full62 audit verified')
