// Copyright 2026 Qore Technologies, s.r.o.; SPDX-License-Identifier: MIT
// Unchanged InlineMacro branch body; observable typed stack, AST and assembler adapters.
#include <cstdio>
#include <cstdlib>
#include <memory>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
void require(bool b) { if (!b) { std::abort(); } }
struct Type { int tag; bool IsNever() const { return tag==0; } bool IsVoid() const { return tag==1; } bool IsConstexpr() const { return tag==3; } bool IsTopType() const { return tag==4; } };
struct TopType:Type { const Type* src; const Type* source_type() const { return src; } static const TopType* cast(const Type* p) { require(p->IsTopType());return static_cast<const TopType*>(p); } };
struct TypeOracle { inline static Type never{0},void_type{1},value{2},constexpr_type{3};static const Type* GetNeverType() { return &never; } };
template<class T> struct Stack:std::vector<T> { void PushMany(const std::vector<T>& x) { this->insert(this->end(),x.begin(),x.end()); } size_t TopRange(size_t n) const { require(n<=this->size());return n; } };
std::vector<const Type*> LowerType(const Type* t) { if(t->IsVoid()||t->IsNever()||t->IsConstexpr()) { return {}; } return {t}; }
struct VisitResult { const Type* type=nullptr;size_t slots=0; VisitResult()=default;VisitResult(const Type* t,size_t s):type(t),slots(s) {} static VisitResult NeverResult() { return {TypeOracle::GetNeverType(),0}; } };
struct Block { Stack<const Type*> stack; };
struct LocalLabel { Block* block;std::vector<const Type*> types; };
struct LabelBindingsManager { static int& Get() { static int m;return m; } };
const char* kMacroEndLabelName="macro_end";
template<class T> struct Binding { T value; Binding(int*,const char*,T v):value(std::move(v)) {} };
struct Signature { const Type* return_type; };
struct Body { const Type* result; unsigned returns; };
struct Macro { Signature sig; Body body_; unsigned returns_=0; const Signature& signature() const { return sig; } const Body* body() const { return &body_; } bool HasReturns() const { return returns_!=0; } void IncrementReturns() { ++returns_; } const char* ReadableName() const { return "control"; } };
[[noreturn]] void ReportError(const std::string& s) { throw std::runtime_error(s); }
struct Assembler { Stack<const Type*> stack;std::unique_ptr<Block> block;unsigned gotos=0,binds=0;Stack<const Type*> CurrentStack() const { return stack; } Block* NewBlock(Stack<const Type*> s) { for(auto* t:s) { require(!t->IsTopType()); } block=std::make_unique<Block>(Block{std::move(s)});return block.get(); } void Goto(Block* p) { require(p==block.get() && p);++gotos; } void Bind(Block* p) { require(p==block.get() && p);++binds; } };
struct ImplementationVisitor {
 Assembler a;VisitResult result;Macro* active;
 Assembler& assembler() { return a; }
 void SetReturnValue(VisitResult v) { result=v; }
 VisitResult GetAndClearReturnValue() { return std::exchange(result,VisitResult{}); }
 const Type* Visit(const Body& b) {
  for(unsigned i=0;i<b.returns;++i) {
   // Mirrors Visit(ReturnStatement)'s precondition before IncrementReturns.
   if(active->signature().return_type->IsNever()) { ReportError("cannot return from a function with return type never"); }
   active->IncrementReturns();
  }
  return b.result;
 }
 __attribute__((noinline)) VisitResult InlineMacro(Macro* macro);
};
VisitResult ImplementationVisitor::InlineMacro(Macro* macro) {
  const Type* return_type = macro->signature().return_type;
  bool can_return = return_type != TypeOracle::GetNeverType();
  Block* macro_end;
  std::optional<Binding<LocalLabel>> macro_end_binding;
  if (can_return) {
    Stack<const Type*> stack = assembler().CurrentStack();
    std::vector<const Type*> lowered_return_types = LowerType(return_type);
    stack.PushMany(lowered_return_types);
    if (!return_type->IsConstexpr()) {
      SetReturnValue(VisitResult(return_type,
                                 stack.TopRange(lowered_return_types.size())));
    }
    // The stack copy used to initialize the _macro_end block is only used
    // as a template for the actual gotos generated by return statements. It
    // doesn't correspond to any real return values, and thus shouldn't contain
    // top types, because these would pollute actual return value types that get
    // unioned with them for return statements, erroneously forcing them to top.
    for (auto i = stack.begin(); i != stack.end(); ++i) {
      if ((*i)->IsTopType()) {
        *i = TopType::cast(*i)->source_type();
      }
    }
    macro_end = assembler().NewBlock(std::move(stack));
    macro_end_binding.emplace(&LabelBindingsManager::Get(), kMacroEndLabelName,
                              LocalLabel{macro_end, {return_type}});
  } else {
    SetReturnValue(VisitResult::NeverResult());
  }

  const Type* result = Visit(*macro->body());

  if (result->IsNever()) {
    if (!return_type->IsNever() && !macro->HasReturns()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " that never returns must have return type never";
      ReportError(s.str());
    }
  } else {
    if (return_type->IsNever()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " has implicit return at end of its declartion but return type "
           "never";
      ReportError(s.str());
    } else if (!macro->signature().return_type->IsVoid()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " expects to return a value but doesn't on all paths";
      ReportError(s.str());
    }
  }
  if (!result->IsNever()) {
    assembler().Goto(macro_end);
  }

  if (macro->HasReturns() || !result->IsNever()) {
    assembler().Bind(macro_end);
  }

  return GetAndClearReturnValue();
}

int main() {
 unsigned cases=0,errors=0;
 for(unsigned repeat=0;repeat<10000;++repeat) {
  for(const Type* declared:{&TypeOracle::never,&TypeOracle::void_type,&TypeOracle::value,&TypeOracle::constexpr_type}) {
   for(const Type* result:{&TypeOracle::never,&TypeOracle::void_type}) {
    for(unsigned returns:{0u,1u,3u}) {
     for(bool top:{false,true}) {
      Macro m{{declared},{result,returns}};ImplementationVisitor v;v.active=&m;
      TopType wrapped{{4},&TypeOracle::value};v.a.stack.push_back(top ? static_cast<const Type*>(&wrapped) : &TypeOracle::value);
      bool bad=(declared->IsNever() && (returns || !result->IsNever())) || (!declared->IsNever() && result->IsNever() && !returns) || (!result->IsNever() && !declared->IsVoid());
      bool rejected=false;
      try { v.InlineMacro(&m); } catch(const std::runtime_error&) { rejected=true;++errors; }
      require(rejected==bad);
      require(bool(v.a.block)==!declared->IsNever());
      if(!bad) {
       require(v.a.gotos==unsigned(!result->IsNever()));
       require(v.a.binds==unsigned(returns || !result->IsNever()));
       require(m.returns_==returns);
       if(v.a.block) { require(v.a.block->stack[0]==&TypeOracle::value); }
      }
      ++cases;
     }
    }
   }
  }
 }
 std::printf("%u macro flow cases pass (%u expected semantic rejections)\n",cases,errors);
}
