# Copyright 2026 Qore Technologies, s.r.o.; SPDX-License-Identifier: MIT
from pathlib import Path
from collections import Counter
import gzip,hashlib,importlib.util,json,re,shutil
root=Path.cwd();out=root/'evidence/controls/nats-memory-create-trace-20261008';out.mkdir(exist_ok=True)
results={}
for name in [t+'-nats-memory-create-trace-268' for t in ('fedora','leap','el10')]+['leap-nats-memory-create-trace-269-group']:
 base=root/'results'/name;status=json.loads((base/'status.json').read_text());assert status['exit_code']==0
 log=(base/'tests.log').read_text();assert 'WARNING: DATA RACE' not in log and '--- FAIL:' not in log
 counts=Counter(re.findall(r'^--- (PASS|SKIP|FAIL):',log,re.M))
 if name.endswith('268'):assert counts=={'PASS':5}
 else:assert sum(counts.values())==73
 results[name]={'exit_code':0,'top_level_results':dict(counts),'source':status['command'][status['command'].index('-run')+1],'test_build':'non-race; upstream target is in a !race file'}
 shutil.copy2(base/'status.json',out/(name+'-status.json'));(out/(name+'.log.gz')).write_bytes(gzip.compress(log.encode(),mtime=0))
for n in (268,269):
 shutil.copy2(root/f'work/prepare-nats-memory-create-trace-{n}-20261008.py',out/f'prepare-{n}.py')
 shutil.copy2(root/f'work/nats-memory-create-trace-{n}.json',out/f'config-{n}.json')
 for p in sorted((root/f'work/nats-memory-create-trace-{n}-20261008').glob('*.go')):(out/(str(n)+'-'+p.name+'.gz')).write_bytes(gzip.compress(p.read_bytes(),mtime=0))
shutil.copy2(root/'work/run-nats-focused-38.py',out/'run.py');shutil.copy2(root/'work/record-nats-memory-create-trace-20261008.py',out/'record.py')
loader=importlib.util.spec_from_file_location('audit',root/'work/write-scoped-audit.py');audit=importlib.util.module_from_spec(loader);loader.loader.exec_module(audit)
passes={9:'New controls and recording scripts carry copyright 2026; upstream source notices are retained.',53:'Trace-only evidence does not propose a fix, change package sources, weaken timeouts, or claim the historical defect resolved.',54:'Bounded log capture uses the existing mutex-protected fixture logger; request workers are joined and all servers/connections have deferred cleanup.',55:'Logger lines are copied under its mutex; existing server/JetStream locks protect the assignment fields recorded by the overlay.',56:'Go channel payloads, stream/error context and source hash records retain their concrete types.',57:'Capture is bounded at 10,000 events per server; no hot-loop polling or additional runtime retries are added.',58:'Every worker result is checked; the full-build recorder preserves all failure statuses and validates complete terminal test coverage.',59:'Evidence explicitly separates passing diagnostic runs from the unresolved historical timeout; it records source-overlay and capture limits.',61:'Controls use isolated offline container networks and contain no credentials; logs are synthetic test data.',62:'Fifteen 250-create controls and the original 73-test group passed. The original timeout is retained as unresolved; no narrow pass is used to qualify the full package.'}
audit.write(out/'audit.rst','NATS creation trace evidence audit','Scope: diagnostic source overlays and evidence records only; no package source or runtime fix. All 62 audit-changes entries reviewed: 10 Pass, 52 N/A, 0 Fail.',passes,'No corresponding Qore module, C++/QPP, cancellation, DataProvider, JNI or public API change in this diagnostic-only scope.')
record={'schema':1,'date':'2026-10-08','copyright':'Copyright 2026 Qore Technologies, s.r.o.','status':'Trace-only controls pass; no historical failure reproduced and no fix claimed. Production package source remains unchanged.','historical_failure':'evidence/nats-candidate46-final-20261008.json','candidate':'evidence/nats-candidate50-preparation-20261008.json','coverage':{'initial_create_runs':15,'streams_per_run':250,'total_initial_creates':3750,'api_deadline_seconds':30,'exact_full_group_tests':73},'results':results,'observability':['API handler entry/return, metadata proposal result, applied assignment, stream leader transition and API response are logged. Failed creates include the stream name.','The complete 73-test group preserves its upstream execution order and original full target including all publications, snapshots and rolling restarts.','The isolated control ends after creation and does not qualify publication/restart.'],'limits':['No pass closes the observed historical timeout. The previous inference that separating publication would remove all creation timeouts is insufficient, as candidate46 demonstrates.','Trace instrumentation and logger locking can affect scheduling. This is a diagnostic candidate, not a production change.','The full passing restart test exceeded the bounded logger capacity on one server after creation; it reported the exact dropped count. Initial failing setup uses fewer than that bound in the isolated runs.','The next diagnostic control tests a real leadership transfer between accepted request and metadata proposal; that possibility is not yet established as the historical cause.'],'audit':{'pass':10,'na':52,'fail':0},'files_sha256':{str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.iterdir())}}
(root/'evidence/nats-memory-create-trace-20261008.json').write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({n:r['top_level_results'] for n,r in results.items()},indent=2))
