# Copyright 2026 Qore Technologies, s.r.o.; SPDX-License-Identifier: MIT
from pathlib import Path
import gzip,hashlib,json,shutil
root=Path.cwd();out=root/'evidence/controls/nats-candidate51-preparation-20261008';out.mkdir()
verification=json.loads((root/'results/nats-candidate51-patch-verification-20261008.json').read_text());assert verification['patches']==114 and verification['exact_focused_source_identity']
for name in ['nats-candidate51-tools-tests-20261008.log','nats-candidate51-runner-tests-20261008.log','nats-candidate51-prepare-20261008.log','nats-candidate51-patches-20261008.log']:
 (out/(name+'.gz')).write_bytes(gzip.compress((root/'results'/name).read_bytes(),mtime=0))
for p in ['results/nats-candidate51-patch-verification-20261008.json','work/prepare-nats-candidate51-20261008.py','work/integrate-nats-create-rejection-20261008.py','work/record-nats-candidate51-preparation-20261008.py','dependencies/nats-server.spec','dependencies/nats-server.rst']:
 shutil.copy2(root/p,out/Path(p).name)
record={'schema':1,'date':'2026-10-08','copyright':'Copyright 2026 Qore Technologies, s.r.o.','status':'Candidate51 prepared from focused-qualified stream-create rejection fix. Historical creation/performance review and full combined qualification remain open; no native build or publication claimed.','qualification':'evidence/nats-create-rejection-20261008.json','patches':114,'fuzz':0,'new_patch_offsets':0,'changed_go_files':verification['changed_go_files_from_candidate50'],'exact_focused_source_identity':True,'tools_tests':218,'runner_tests':7,'bundle':'work/nats-server-candidate-51','prepared_source':'work/nats-prepared-51/nats-server-2.15.0','documentation':'Dependency guide now describes the current candidate and open gates; the superseded claim about changed distributed response ownership has been removed.','remaining':['Establish historical 250-concurrent-stream and atomic initial-create failure paths; proposal rejection fix does not by itself prove those causes.','Resolve the sparse-consumer performance gate without weakening the workload or bound.','Run the full combined RPM matrix, native x86_64/aarch64 OBS builds, installed client/Qore module and repository lifecycle/signing/publication qualification.'],'files_sha256':{str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.iterdir())}}
(root/'evidence/nats-candidate51-preparation-20261008.json').write_text(json.dumps(record,indent=2)+'\n');print('Recorded candidate51 source identity, all patch checks and 225 passing packaging tests.')
